version: "3"

services:
  database:
    container_name: postgree
    image: postgres:alpine3.18
    ports:
      - 8082:5432
    volumes:
      - postg:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=userpass

  pgAdmin:
    depends_on:
      - database
    container_name: pgadminn
    image: dpage/pgadmin4:7.3
    ports:
      - 8083:80
    volumes:
      - ./pgAdmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_PASSWORD=user_pass
      - PGADMIN_DEFAULT_EMAIL=jaredbastarracheas@gmail.com

volumes:
  postg:
    external: true